### ISSUE TITLE
Dropbox papers are editable

### ISSUE THREAD

**Issue by bbdaniels** [worldbank/DIME-MSIE-Workshop#4]
Dropbox paper sharing settings are currently "anyone with the link", so people who reach them from this page can edit. Should these be changed to invitation-only?

**Comment by kbjarkefur** [comment]
Can they be changed to:
* `write`: invitation-only
* `read`: anyone with link
That should be possible in DBpaper, and should solve the issue, right?

**Comment by kbjarkefur** [comment]
This is now changed for the dropbox paper links that are currently linked to!
