### ISSUE TITLE
Change Hands-on-Sessions to "Interactives"?

### ISSUE THREAD

**Issue by bbdaniels** [worldbank/DIME-MSIE-Workshop#5]
Potentially neater folder naming structure.

**Comment by kbjarkefur** [comment]
we kind of established that name, but I see what you are saying. would `HandsOn` be a compromise?

**Comment by bbdaniels** [comment]
Acually just `hands-on` could be fine, it makes sense in both English and code

**Comment by kbjarkefur** [comment]
solved in c76823407b1b21f3920af1e2205bc530729bfbe2
